export const ANIMAL_TYPE = 'ANIMAL_TYPE';
export const SET_DONATION_VALUE = 'SET_DONATION_VALUE';
export const SET_TO_REGULAR_DONATION = 'SET_TO_REGULAR_DONATION';
export const REMEMBER_LAST_DONATION_VALUE = 'REMEMBER_LAST_DONATION_VALUE';
export const SUBMIT_DONATION = 'SUBMIT_DONATION';