version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
#      - run:
#          name: Clean node Cache
#          command: 'sudo npm cache clean --force'
#      - run:
#          name: Install n module
#          command: 'sudo npm install -g n'
#      - run:
#          name: Install stable Node version Using n Module
#          command: 'sudo n stable'
#      - run:
#          name: update-npm
#          command: 'sudo npm install -g npm@5'
       - run:
           name: install-npm
           command: npm install
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Test
          command: npm run test
      - run:
          name: Code-coverage
          command: './node_modules/.bin/nyc report --reporter=text-lcov'
      - store_artifacts:
          path: test-results.xml
          prefix: tests
      - store_artifacts:
          path: coverage
          prefix: coverage
      - store_test_results:
          path: test-results.xml