version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.7.4
      - image: mongo:3.4.4
    steps:
      - checkout
      - run:
          name: Clear cache
          command: 'npm cache clean --force'
      - run:
          name: Update-npm
          command: 'sudo npm install -g npm@6'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Test
          command: npm run test-ci
      - run:
          name: Code-coverage
          command: './node_modules/.bin/nyc report --reporter=text-lcov'
      - store_artifacts:
          path: test-results.xml
          prefix: tests
      - store_artifacts:
          path: coverage
          prefix: coverage
      - store_test_results:
          path: test-results.xml